#!/usr/bin/env python
"""Semantic and morphological rules governing gender class assignment for German nouns"""

# MASCULINE

masc_classes = [
    # animals
    "animal",
    "beast",
    # times of the day
    "time period",
    "period of time",
    "time",
    "time of day" "period",
    # days of the week
    "weekday",
    "civil day",
    "calendar day",
    "day of the week",
    # months
    "month",
    "Gregorian calendar month",
    "calendar month",
    # seasons
    "season",
    "time of year",
    # points on the compass
    "compass point",
    "cardinal compass point",
    "spatial relation",
    "geographical point",
    # precipitation and wind
    "natural event",
    "weather condition",
    "precipitation",
    "atmospheric phenomenon",
    "weather",
    "atmospheric condition",
    "wind",
    "windstorm",
    "cyclone",
    "storm",
    "natural phenomenon",
    # celestial bodies
    "minor planet",
    "celestial body",
    "planetoid",
    "heavenly body",
    "planet",
    "satellite",
    # types of soil, minerals and rock
    "jewel",
    "stone",
    "Earth's surface",
    "ground",
    "earth",
    "surface",
    "solid",
    "soil",
    "transparent gem",
    "gem",
    "precious stone",
    "gemstone",
    "crystal",
    "mineral",
    # dirt and waste
    "waste",
    "dirt",
    "incautiousness",
    "imprudence",
    "carelessness",
    "worthlessness",
    "ineptitude",
    "waste product",
    "waste material",
    "waste matter",
    "excrement",
    "dejection",
    "uncleanness",
    "dirtiness",
    # bodies of water
    "body of water",
    "water",
    # mountains and peaks
    "elevation",
    "mountain",
    "topographic point",
    "natural elevation",
    "formation",
    # cloth and fabric
    "fabric",
    "cloth",
    "material",
    "textile",
    # types of fish
    "fish",
    "aquatic vertebrate",
    # plants, vegetables, salads, and spices
    "vegetable",
    "plant",
    "herb",
    "plant material",
    "herbaceous plant",
    "salad",
    "veggie",
    "seasoning",
    "mushroom",
    "fungus",
    "cereal",
    # coffee and tea
    "coffee",
    "tea",
    # alcoholic beverages
    "alcohol",
    "alcoholic beverage",
    "drink",
    "alcoholic drink",
    "inebriant",
    "intoxicant",
    "spirit",
    "spirits",
    "liquor",
    "hard drink",
    "strong drink",
    # equipment, instruments, tools
    "instrumentality",
    "instrumentation",
    "device",
    "implement",
    # cars
    "wheeled vehicle",
    "self-propelled vehicle",
    "motortruck",
    "truck",
    "motor vehicle",
    # currencies
    "monetary unit",
    # types of music
    "music genre",
    "musical genre",
    "music",
    # dance
    "dance",
    "dance music",
    "dancing",
    # masculine persons
    "male",
]

masc_category_dict = {
    "animals": ["animal", "beast"],
    "times of the day": [
        "time period",
        "period of time",
        "time",
        "time of day" "period",
    ],
    "days of the week": ["weekday", "civil day", "calendar day", "day of the week"],
    "months": ["month", "Gregorian calendar month", "calendar month"],
    "seasons": ["season", "time of year"],
    "points on the compass": [
        "compass point",
        "cardinal compass point",
        "spatial relation",
        "geographical point",
    ],
    "precipitation and wind": [
        "natural event",
        "weather condition",
        "precipitation",
        "atmospheric phenomenon",
        "weather",
        "atmospheric condition",
        "wind",
        "windstorm",
        "cyclone",
        "storm",
        "natural phenomenon",
    ],
    "celestial bodies": [
        "minor planet",
        "celestial body",
        "planetoid",
        "heavenly body",
        "planet",
        "satellite",
    ],
    "types of soil, minerals and rock": [
        "jewel",
        "stone",
        "Earth's surface",
        "ground",
        "earth",
        "surface",
        "solid",
        "soil",
        "transparent gem",
        "gem",
        "precious stone",
        "gemstone",
        "crystal",
        "mineral",
    ],
    "dirt and waste": [
        "waste",
        "dirt",
        "incautiousness",
        "imprudence",
        "carelessness",
        "worthlessness",
        "ineptitude",
        "waste product",
        "waste material",
        "waste matter",
        "excrement",
        "dejection",
        "uncleanness",
        "dirtiness",
    ],
    "bodies of water": ["body of water", "water"],
    "mountains and peaks": [
        "elevation",
        "mountain",
        "topographic point",
        "natural elevation",
        "formation",
    ],
    "cloth and fabric": ["fabric", "cloth", "material", "textile"],
    "types of fish": ["fish", "aquatic vertebrate"],
    "plants, vegetables, salads, and spices": [
        "vegetable",
        "plant",
        "herb",
        "plant material",
        "herbaceous plant",
        "salad",
        "veggie",
        "seasoning",
        "mushroom",
        "fungus",
        "cereal",
    ],
    "coffee and tea": ["coffee", "tea"],
    "alcoholic beverages": [
        "alcohol",
        "alcoholic beverage",
        "drink",
        "alcoholic drink",
        "inebriant",
        "intoxicant",
        "spirit",
        "spirits",
        "liquor",
        "hard drink",
        "strong drink",
    ],
    "equipment, instruments, tools": [
        "instrumentality",
        "instrumentation",
        "device",
        "implement",
    ],
    "cars": [
        "wheeled vehicle",
        "self-propelled vehicle",
        "motortruck",
        "truck",
        "motor vehicle",
    ],
    "currencies": ["monetary unit"],
    "types of music": ["music genre", "musical genre", "music"],
    "dance": ["dance", "dance music", "dancing"],
    "masculine persons": ["male"],
}

"""
Due to the lack of synsets, the following typically masculine semantic categories were unaccounted for:
- names of rivers outside of Central Europe
- elongated shapes
- names of car brands
- names of trains
"""

masc_suffixes = [
    "aal",
    "ag",
    "all",
    "am",
    "an",
    "ang",
    "ant",
    "ast",
    "auch",
    "aum",
    "bold",
    "eg",
    "eis",
    "en",
    "ent",
    "er",
    "el",
    "eur",
    "ich",
    "ig",
    "iker",
    "ismus",
    "ling",
    "mpf",
    "ner",
    "og",
    "on",
    "pf",
    "tel",
    "u",
    "uch",
    "ug",
    "und",
    "us",
    "wart",
    "x",
    # composite noun endings
    "staat",
    "markt",
    "saft",
    "kuchen",
    "tee",
    "kaffee",
    "wert",
    "test",
    "draht",
    "bart",
    "start",
    "hut",
    "ball",
    "sport",
    "rat",
]

masc_prefixes = ["Kn", "Schwa"]

# FEMININE

fem_classes = [
    # numbers and mathematics
    "measure",
    "number",
    "integer",
    "quantity",
    "maths",
    "math",
    "mathematics",
    "charge",
    # time
    "time unit",
    "period",
    "time period",
    "unit of time",
    "point in time",
    "time",
    # authority, power, and governance
    "strength",
    "action",
    "causal agency",
    "power",
    "causal agent",
    "powerfulness",
    "control",
    "governance",
    "authority",
    # rules, permission, and limits
    "rule",
    "noesis",
    "control",
    "direction",
    "authorization",
    "empowerment",
    "boundary",
    "limit",
    "edge",
    "demarcation",
    # knowledge and wisdom
    "idea",
    "content",
    "cognitive content",
    "cognition",
    "knowldege",
    "psychological feature",
    "discernment",
    "wiseness",
    "wisdom",
    "judiciousness",
    "judgment",
    # communication
    "connection",
    "communication",
    "relation",
    "connectedness",
    "speech",
    "speech production",
    "utterance",
    "speech act",
    # musical instruments
    "instrument",
    "musical instrument",
    # form and shape
    "structure",
    "spatial property",
    "visual aspect",
    "spatiality",
    "shape",
    "form",
    "ridge",
    "surface",
    # hollow shapes
    "container",
    "containerful",
    "plumbing fixture",
    "cave",
    "cylinder",
    # food
    "fare",
    "food",
    "fasting",
    "nutrient",
    "sustenance",
    "foodstuff",
    "nutrition",
    "nourishment",
    "food product",
    "nutriment",
    # gestures and motions
    "motion",
    "movement",
    "move",
    "attitude",
    # sailing craft and water craft
    "watercraft",
    # temperature (hot v. cold)
    "temperature",
    "somatic sensation",
    "physiological condition",
    # aircraft
    "heavier-than-air craft",
    "aircraft",
    "aeroplane",
    "plane",
    "airplane",
    # small birds
    "bird",
    # insects
    "insect",
    "invertebrate",
    # trees
    "woody plant",
    "tree",
    # flowers
    "flowering tree",
    "flower",
    "flower bud",
    # fruit
    "edible fruit",
    "fruit",
    # typeface
    "font",
    "typeface",
    # software
    "computer code",
    "computer",
    "code",
    "coding system",
    "computer program",
    "software system",
    "program",
    "software",
    # female persons
    "female",
    "woman",
    "female person",
]

fem_category_dict = {
    "numbers and mathematics": [
        "measure",
        "number",
        "integer",
        "quantity",
        "maths",
        "math",
        "mathematics",
        "charge",
    ],
    "time": [
        "time unit",
        "period",
        "time period",
        "unit of time",
        "point in time",
        "time",
    ],
    "authority, power, and governance": [
        "strength",
        "action",
        "causal agency",
        "power",
        "causal agent",
        "powerfulness",
        "control",
        "governance",
        "authority",
    ],
    "rules, permission, and limits": [
        "rule",
        "noesis",
        "control",
        "direction",
        "authorization",
        "empowerment",
        "boundary",
        "limit",
        "edge",
        "demarcation",
    ],
    "knowledge and wisdom": [
        "idea",
        "content",
        "cognitive content",
        "cognition",
        "knowldege",
        "psychological feature",
        "discernment",
        "wiseness",
        "wisdom",
        "judiciousness",
        "judgment",
    ],
    "communication": [
        "connection",
        "communication",
        "relation",
        "connectedness",
        "speech",
        "speech production",
        "utterance",
        "speech act",
    ],
    "musical instruments": ["instrument", "musical instrument"],
    "form and shape": [
        "structure",
        "spatial property",
        "visual aspect",
        "spatiality",
        "shape",
        "form",
        "ridge",
        "surface",
    ],
    "hollow shapes": [
        "container",
        "containerful",
        "plumbing fixture",
        "cave",
        "cylinder",
    ],
    "food": [
        "fare",
        "food",
        "fasting",
        "nutrient",
        "sustenance",
        "foodstuff",
        "nutrition",
        "nourishment",
        "food product",
        "nutriment",
    ],
    "gestures and motions": ["motion", "movement", "move", "attitude"],
    "sailing craft and water craft": ["watercraft"],
    "temperature": ["temperature", "somatic sensation", "physiological condition"],
    "aircraft": [
        "heavier-than-air craft",
        "aircraft",
        "aeroplane",
        "plane",
        "airplane",
    ],
    "small birds": ["bird"],
    "insects": ["insect", "invertebrate"],
    "trees": ["woody plant", "tree"],
    "flowers": ["flowering tree", "flower", "flower bud"],
    "fruit": ["edible fruit", "fruit"],
    "typeface": ["font", "typeface"],
    "software": [
        "computer code",
        "computer",
        "code",
        "coding system",
        "computer program",
        "software system",
        "program",
        "software",
    ],
    "female persons": ["female", "woman", "female person"],
}

"""
Due to the lack of synsets, the following typically feminine semantic categories were unaccounted for:
- flat shapes
- sharp shapes
- pincer shapes
- most rivers in Central Europe
- hunting and things related to hunting
- temperature (no synsets for hot and cold things)
- motorcycle brands
"""

fem_suffixes = [
    "a",
    "acht",
    "ade",
    "age",
    "anz",
    "art",
    "e",
    "ee",
    "ei",
    "erei",
    "enz",
    "falt",
    "grafie",
    "graphie",
    "heit",
    "icht",
    "ie",
    "ik",
    "in",
    "itis",
    "tis",
    "keit",
    "logie",
    "t",
    "ft",
    "cht",
    "orm",
    "tät",
    "thek",
    "igion",
    "lion",
    "nion",
    "sion",
    "tion",
    "xion",
    "schaft",
    "sis",
    "ung",
    "ur",
    "ür",
    # composite noun endings
    "tat",
]

# NEUTER

neut_classes = [
    # higher-level or first-order categories or collections of things
    "aggregation",
    "group",
    "accumulation",
    "grouping",
    "assemblage",
    "collection",
    "whole",
    "abstraction",
    "entity",
    # letters of the alphabet
    "written symbol",
    "symbol",
    "graphic symbol",
    "letter",
    "sign",
    "character",
    "grapheme",
    # languages
    "language",
    "natural language",
    # grammatical terms and POS
    "syntactic category",
    "linguistic unit",
    "word class",
    "part of speech",
    "grammatical category",
    # colors
    "color",
    "colour",
    # human and animal babies
    "kid",
    "child",
    "progeny",
    "offspring",
    "young",
    # pieces and particles
    "relation",
    "part",
    "fraction",
    "percentage",
    "portion",
    "component",
    "constituent",
    "element"
    # elements of the Periodic Table
    "chemical element",
    # types of metals
    "metal"
    # materials
    "material",
    "substance",
    "matter",
    # units of measurement
    "potential unit",
    "definite quantity",
    "unit of measurement",
    "amount",
    "quantity",
    "measure",
    "unit"
    # music settings and instruments
    "performance",
    "musical group",
    "musical organization",
    "music",
    "musical instrument",
    # fractions
    "fraction",
    # books, paper, writing
    "writing",
    "paper",
    # sport and games
    "exercise",
    "physical exertion",
    "exercising",
    "workout",
    "exertion",
    "game",
    "sport",
    # Mecicine
    "drug",
    "medicine",
    "medicament",
]

neut_category_dict = {
    "higher-level or first-order categories or collections of things": [
        "aggregation",
        "group",
        "accumulation",
        "grouping",
        "assemblage",
        "collection",
        "whole",
        "abstraction",
        "entity",
    ],
    "letters of the alphabet": [
        "written symbol",
        "symbol",
        "graphic symbol",
        "letter",
        "sign",
        "character",
        "grapheme",
    ],
    "languages": ["language", "natural language"],
    "grammatical terms and POS": [
        "syntactic category",
        "linguistic unit",
        "word class",
        "part of speech",
        "grammatical category",
    ],
    "colors": ["color", "colour"],
    "human and animal babies": ["kid", "child", "progeny", "offspring", "young"],
    "pieces and particles": [
        "relation",
        "part",
        "fraction",
        "percentage",
        "portion",
        "component",
        "constituent",
        "element",
    ],
    "elements of the Periodic Table": ["chemical element"],
    "types of metals": ["metal"],
    "materials": ["material", "substance", "matter"],
    "units of measurement": [
        "potential unit",
        "definite quantity",
        "unit of measurement",
        "amount",
        "quantity",
        "measure",
        "unit",
    ],
    "music settings and instruments": [
        "performance",
        "musical group",
        "musical organization",
        "music",
        "musical instrument",
    ],
    "fractions": ["fraction"],
    "books, paper, writing": ["writing", "paper"],
    "sport and games": [
        "exercise",
        "physical exertion",
        "exercising",
        "workout",
        "exertion",
        "game",
        "sport",
    ],
    "Medicine": ["drug", "medicine", "medicament"],
}

"""
Due to the lack of synsets, the following typically neuter semantic categories were unaccounted for:
- nouns derived from adjectives
- names of continents, countries, regions, cities, and valleys
- types of grass
- types of detergents
- names of hotels, cafes, clubs, theaters, and cinemas
"""

neut_suffixes = [
    "en",  # takes care of the gerunds
    "ien",
    "land",
    "reich",
    "stan",
    "chen",
    "lein",
    "le",
    "erl",
    "el",
    "li",
    "aar",
    "är",
    "al",
    "at",
    "bot",
    "eil",
    "em",
    "ett",
    "euer",
    "fon",
    "phon",
    "gramm",
    "horn",
    "ial",
    "iel",
    "ier",
    "ing",
    "ip",
    "iv",
    "ld",
    "ma",
    "ment",
    "nis",
    "ol",
    "om",
    "ym",
    "skop",
    "tum",
    "um",
    "werk",
    "yl",
    "zept",
    "zeug"
    # composite noun endings
    "wasser",
    "feuer",
    "buch",
    "word",
    "mittel",
]

neut_prefixes = ["Ge"]
