#!/usr/bin/env python
"""Semantic and morphological rules governing gender class assignment for German nouns"""

# MASCULINE

masc_classes = [
    "animal",
    "time period",
    "weekday",
    "month",
    "season",
    "compass point",
    "precipitation",
    "atmospheric phenomenon",
    "celestial body",
    "jewel",
    "stone",
    "waste",
    "body of water",
    "elevation",
    "fabric",
    "cloth",
    "fish",
    "vegetable",
    "plant",
    "herb",
    "coffee",
    "tea",
    "alcohol",
    "instrumentality",
    "wheeled vehicle",
    "monetary unit",
    "music genre",
    "dance",
    "male",
]

masc_suffixes = [
    "aal",
    "ag",
    "all",
    "am",
    "an",
    "ang",
    "ant",
    "ast",
    "auch",
    "aum",
    "bold",
    "eg",
    "eis",
    "en",
    "ent",
    "er",
    "el",
    "eur",
    "ich",
    "ig",
    "iker",
    "ismus",
    "ling",
    "mpf",
    "ner",
    "og",
    "on",
    "pf",
    "tel",
    "u",
    "uch",
    "ug",
    "und",
    "us",
    "wart"
    "x",
    # composite noun endings
    "staat", 
    "markt", 
    "saft", 
    "wert", 
    "test", 
    "draht", 
    "bart", 
    "start", 
    "hut",
    "ball",
    "sport",
    "rat"
]

masc_prefixes = ["kn", "schwa"]

# FEMININE

fem_classes = [
    # numbers and mathematics
    "measure",
    "number",
    "integer",
    "quantity",
    "maths",
    "math",
    "mathematics",
    "charge",
    # time
    "time unit",
    "period",
    "time period",
    "unit of time",
    "point in time",
    "time",
    # authority, power, and governance
    "strength",
    "action",
    "causal agency",
    "power",
    "causal agent",
    "powerfulness",
    "control",
    "governance",
    "authority",
    # rules, permission, and limits
    "rule",
    "noesis",
    "control",
    "direction",
    "authorization",
    "empowerment",
    "boundary",
    "limit",
    "edge",
    "demarcation",
    # knowledge and wisdom
    "idea",
    "content",
    "cognitive content",
    "cognition",
    "knowldege",
    "psychological feature",
    "discernment",
    "wiseness",
    "wisdom",
    "judiciousness",
    "judgment",
    # communication
    "connection",
    "communication",
    "relation",
    "connectedness",
    "speech",
    "speech production",
    "utterance",
    "speech act",
    # musical instruments
    "instrument",
    "musical instrument",
    # form and shape
    "structure",
    "spatial property",
    "visual aspect",
    "spatiality",
    "shape",
    "form",
    "ridge",
    "surface",
    # hollow shapes
    "container",
    "containerful",
    "plumbing fixture",
    "cave",
    "cylinder",
    # food
    "fare",
    "food",
    "fasting",
    "nutrient",
    "sustenance",
    "foodstuff",
    "nutrition",
    "nourishment",
    "food product",
    "nutriment",
    # gestures and motions
    "motion",
    "movement",
    "move",
    "attitude",
    # sailing craft and water craft
    "watercraft",
    # temperature (hot v. cold)
    "temperature",
    "somatic sensation",
    "physiological condition",
    # aircraft
    "heavier-than-air craft",
    "aircraft",
    "aeroplane",
    "plane",
    "airplane",
    # small birds
    "bird",
    # insects
    "insect",
    "invertebrate",
    # trees
    "woody plant",
    "tree",
    # flowers
    "flowering tree",
    "flower",
    "flower bud",
    # fruit
    "edible fruit",
    "fruit",
    # typeface
    "font",
    "typeface",
    # software
    "computer code",
    "computer",
    "code",
    "coding system",
    "computer program",
    "software system",
    "program",
    "software",
    # female persons
    "female",
    "woman",
    "female person",
]

fem_category_dict = {
    "numbers and mathematics": [
        "measure",
        "number",
        "integer",
        "quantity",
        "maths",
        "math",
        "mathematics",
        "charge",
    ],
    "time": [
        "time unit",
        "period",
        "time period",
        "unit of time",
        "point in time",
        "time",
    ],
    "authority, power, and governance": [
        "strength",
        "action",
        "causal agency",
        "power",
        "causal agent",
        "powerfulness",
        "control",
        "governance",
        "authority",
    ],
    "rules, permission, and limits": [
        "rule",
        "noesis",
        "control",
        "direction",
        "authorization",
        "empowerment",
        "boundary",
        "limit",
        "edge",
        "demarcation",
    ],
    "knowledge and wisdom": [
        "idea",
        "content",
        "cognitive content",
        "cognition",
        "knowldege",
        "psychological feature",
        "discernment",
        "wiseness",
        "wisdom",
        "judiciousness",
        "judgment",
    ],
    "communication": [
        "connection",
        "communication",
        "relation",
        "connectedness",
        "speech",
        "speech production",
        "utterance",
        "speech act",
    ],
    "musical instruments": ["instrument", "musical instrument"],
    "form and shape": [
        "structure",
        "spatial property",
        "visual aspect",
        "spatiality",
        "shape",
        "form",
        "ridge",
        "surface",
    ],
    "hollow shapes": [
        "container",
        "containerful",
        "plumbing fixture",
        "cave",
        "cylinder",
    ],
    "food": [
        "fare",
        "food",
        "fasting",
        "nutrient",
        "sustenance",
        "foodstuff",
        "nutrition",
        "nourishment",
        "food product",
        "nutriment",
    ],
    "gestures and motions": ["motion", "movement", "move", "attitude"],
    "sailing craft and water craft": ["watercraft"],
    "temperature": ["temperature", "somatic sensation", "physiological condition"],
    "aircraft": [
        "heavier-than-air craft",
        "aircraft",
        "aeroplane",
        "plane",
        "airplane",
    ],
    "small birds": ["bird"],
    "insects": ["insect", "invertebrate"],
    "trees": ["woody plant", "tree"],
    "flowers": ["flowering tree", "flower", "flower bud"],
    "fruit": ["edible fruit", "fruit"],
    "typeface": ["font", "typeface"],
    "software": [
        "computer code",
        "computer",
        "code",
        "coding system",
        "computer program",
        "software system",
        "program",
        "software",
    ],
    "female persons": ["female", "woman", "female person"],
}

fem_suffixes = [
    "a",
    "acht",
    "ade",
    "age",
    "anz",
    "art",
    "e",
    "ee",
    "ei",
    "erei",
    "enz",
    "falt",
    "grafie",
    "graphie",
    "heit",
    "icht",
    "ie",
    "ik",
    "in",
    "itis",
    "tis",
    "keit",
    "logie",
    "t",
    "ft",
    "cht",
    "orm",
    "tät",
    "thek",
    "igion",
    "lion",
    "nion",
    "sion",
    "tion",
    "xion",
    "schaft",
    "sis",
    "ung",
    "ur",
    "ür",
    # composite noun endings
    "tat"
]

# NEUTER

neut_classes = [
    # higher-level or first-order categories or collections of things
    "aggregation",
    "group",
    "accumulation",
    "grouping",
    "assemblage",
    "collection",
    "whole",
    "abstraction",
    "entity",
    # letters of the alphabet
    "written symbol",
    "symbol",
    "graphic symbol",
    "letter",
    "sign",
    "character",
    "grapheme",
    # languages
    "language",
    "natural language",
    # grammatical terms and POS
    "syntactic category",
    "linguistic unit",
    "word class",
    "part of speech",
    "grammatical category",
    # colors
    "color",
    "colour",
    # human and animal babies
    "kid",
    "child",
    "progeny",
    "offspring",
    "young",
    # pieces and particles
    "relation",
    "part",
    "fraction",
    "percentage",
    "portion",
    "component",
    "constituent",
    "element"
    # elements of the Periodic Table
    "chemical element",
    # types of metals
    "metal"
    # materials
    "material",
    "substance",
    "matter",
    # units of measurement
    "potential unit",
    "definite quantity",
    "unit of measurement",
    "amount",
    "quantity",
    "measure",
    "unit"
    # music settings and instruments
    "performance",
    "musical group",
    "musical organization",
    "music",
    "musical instrument",
    # fractions
    "fraction",
    # books, paper, writing
    "writing",
    "paper",
    # sport and games
    "exercise",
    "physical exertion",
    "exercising",
    "workout",
    "exertion",
    "game",
    "sport",
    # Mecicine
    "drug",
    "medicine",
    "medicament"    
]

neut_category_dict = {

}

neut_suffixes = [
    "en", # takes care of the gerunds
    "ien",
    "land",
    "reich",
    "stan",
    "chen",
    "lein",
    "le",
    "erl",
    "el",
    "li",
    "aar",
    "är",
    "al",
    "at",
    "bot",
    "eil",
    "em",
    "ett",
    "euer",
    "fon",
    "phon",
    "gramm",
    "horn",
    "ial",
    "iel",
    "ier",
    "ing",
    "ip",
    "iv",
    "ld",
    "ma",
    "ment",
    "nis",
    "ol",
    "om",
    "ym",
    "skop",
    "tum",
    "um",
    "werk",
    "yl",
    "zept",
    "zeug"
    # composite noun endings
    "wasser", 
    "feuer", 
    "buch", 
    "word",
    "mittel"
]

neut_prefixes = [
    "ge"
]
