#!/usr/bin/env python
"""Semantic and morphological rules governing gender class assignment for German nouns"""

# MASCULINE

masc_classes = [
    "animal",
    "time period",
    "weekday",
    "month",
    "season",
    "compass point",
    "precipitation",
    "atmospheric phenomenon",
    "celestial body",
    "jewel",
    "stone",
    "waste",
    "body of water",
    "elevation",
    "fabric",
    "cloth",
    "fish",
    "vegetable",
    "plant",
    "herb",
    "coffee",
    "tea",
    "alcohol",
    "instrumentality",
    "wheeled vehicle",
    "monetary unit",
    "music genre",
    "dance",
    "male",
]

masc_suffixes = [
    "aal",
    "ag",
    "all",
    "am",
    "an",
    "ang",
    "ant",
    "ast",
    "auch",
    "aum",
    "bold",
    "eg",
    "eis",
    "en",
    "ent",
    "er",
    "el",
    "eur",
    "ich",
    "ig",
    "iker",
    "ismus",
    "ling",
    "mpf",
    "ner",
    "og",
    "on",
    "pf",
    "tel",
    "u",
    "uch",
    "ug",
    "und",
    "us",
    "staat",
    "markt",
    "saft",
    "wert",
    "test",
    "draht",
    "bart",
    "start",
    "wart",
    "hut",
    "x",
]

masc_prefixes = ["kn", "schwa"]

# FEMININE

fem_classes = [
    # numbers and mathematics
    "measure",
    "number",
    "integer",
    "quantity",
    "maths",
    "math",
    "mathematics",
    "charge",
    # time
    "time unit",
    "period",
    "time period",
    "unit of time",
    "point in time",
    "time",
    # authority, power, and governance
    "strength",
    "action",
    "causal agency",
    "power",
    "causal agent",
    "powerfulness",
    "control",
    "governance",
    "authority",
    # rules, permission, and limits
    "rule",
    "noesis",
    "control",
    "direction",
    "authorization",
    "empowerment",
    "boundary",
    "limit",
    "edge",
    "demarcation",
    # knowledge and wisdom
    "idea",
    "content",
    "cognitive content",
    "cognition",
    "knowldege",
    "psychological feature",
    "discernment",
    "wiseness",
    "wisdom",
    "judiciousness",
    "judgment",
    # communication
    "connection",
    "communication",
    "relation",
    "connectedness",
    "speech",
    "speech production",
    "utterance",
    "speech act",
    # musical instruments
    "instrument",
    "musical instrument",
    # form and shape
    "structure",
    "spatial property",
    "visual aspect",
    "spatiality",
    "shape",
    "form",
    "ridge",
    "surface",
    # hollow shapes
    "container",
    "containerful",
    "plumbing fixture",
    "cave",
    "cylinder",
    # food
    "fare",
    "food",
    "fasting",
    "nutrient",
    "sustenance",
    "foodstuff",
    "nutrition",
    "nourishment",
    "food product",
    "nutriment",
    # gestures and motions
    "motion",
    "movement",
    "move",
    "attitude",
    # sailing craft and water craft
    "watercraft",
    # temperature (hot v. cold)
    "temperature",
    "somatic sensation",
    "physiological condition",
    # aircraft
    "heavier-than-air craft",
    "aircraft",
    "aeroplane",
    "plane",
    "airplane",
    # small birds
    "bird",
    # insects
    "insect",
    "invertebrate",
    # trees
    "woody plant",
    "tree",
    # flowers
    "flowering tree",
    "flower",
    "flower bud",
    # fruit
    "edible fruit",
    "fruit",
    # typeface
    "font",
    "typeface",
    # software
    "computer code",
    "computer",
    "code",
    "coding system",
    "computer program",
    "software system",
    "program",
    "software",
    # female persons
    "female",
    "woman",
    "female person",
]

fem_category_dict = {
    "numbers and mathematics": [
        "measure",
        "number",
        "integer",
        "quantity",
        "maths",
        "math",
        "mathematics",
        "charge",
    ],
    "time": [
        "time unit",
        "period",
        "time period",
        "unit of time",
        "point in time",
        "time",
    ],
    "authority, power, and governance": [
        "strength",
        "action",
        "causal agency",
        "power",
        "causal agent",
        "powerfulness",
        "control",
        "governance",
        "authority",
    ],
    "rules, permission, and limits": [
        "rule",
        "noesis",
        "control",
        "direction",
        "authorization",
        "empowerment",
        "boundary",
        "limit",
        "edge",
        "demarcation",
    ],
    "knowledge and wisdom": [
        "idea",
        "content",
        "cognitive content",
        "cognition",
        "knowldege",
        "psychological feature",
        "discernment",
        "wiseness",
        "wisdom",
        "judiciousness",
        "judgment",
    ],
    "communication": [
        "connection",
        "communication",
        "relation",
        "connectedness",
        "speech",
        "speech production",
        "utterance",
        "speech act",
    ],
    "musical instruments": ["instrument", "musical instrument"],
    "form and shape": [
        "structure",
        "spatial property",
        "visual aspect",
        "spatiality",
        "shape",
        "form",
        "ridge",
        "surface",
    ],
    "hollow shapes": [
        "container",
        "containerful",
        "plumbing fixture",
        "cave",
        "cylinder",
    ],
    "food": [
        "fare",
        "food",
        "fasting",
        "nutrient",
        "sustenance",
        "foodstuff",
        "nutrition",
        "nourishment",
        "food product",
        "nutriment",
    ],
    "gestures and motions": ["motion", "movement", "move", "attitude"],
    "sailing craft and water craft": ["watercraft"],
    "temperature": ["temperature", "somatic sensation", "physiological condition"],
    "aircraft": [
        "heavier-than-air craft",
        "aircraft",
        "aeroplane",
        "plane",
        "airplane",
    ],
    "small birds": ["bird"],
    "insects": ["insect", "invertebrate"],
    "trees": ["woody plant", "tree"],
    "flowers": ["flowering tree", "flower", "flower bud"],
    "fruit": ["edible fruit", "fruit"],
    "typeface": ["font", "typeface"],
    "software": [
        "computer code",
        "computer",
        "code",
        "coding system",
        "computer program",
        "software system",
        "program",
        "software",
    ],
    "female persons": ["female", "woman", "female person"],
}

fem_suffixes = [
    "a",
    "acht",
    "ade",
    "age",
    "anz",
    "art",
    "e",
    "ee",
    "ei",
    "erei",
    "enz",
    "falt",
    "grafie",
    "graphie",
    "heit",
    "icht",
    "ie",
    "ik",
    "in",
    "itis",
    "tis",
    "keit",
    "logie",
    "t",
    "ft",
    "cht",
    "orm",
    "tät",
    "thek",
    "igion",
    "lion",
    "nion",
    "sion",
    "tion",
    "xion",
    "schaft",
    "sis",
    "ung",
    "ur",
    "ür",
]
